pull_request_rules:
  - name: Automatic merge
    description: Merge flake.lock updates
    conditions:
      - author = github-actions[bot]
      - modified-files = Updates
    actions:
      merge:
