name: Checks
on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [main]
    paths:
      - "**/*.nix"
      - "flake.lock"

jobs:
  nix:
    name: Nix Flake Checks
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v3
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-platforms = aarch64-linux
      - uses: actions/checkout@v5
      - name: Run nix flake check
        run: nix flake check --all-systems
