name: Updates
on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  nix-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: DeterminateSystems/nix-installer-action@v19
      - name: Update packages
        run: |
          set -Eeu
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          nix eval --json .#packageList | nix run nixpkgs#jq -- -r '.[]' | while read i; do
            nix run nixpkgs#nix-update -- $i --flake --commit --version=branch
          done
          nix flake update --commit-lock-file
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ci/update
          delete-branch: true
          title: "Updates"
          body: |
            Update everything

            See commit messages for details
